/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KotonohaConsolePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/cli/runKotonoha.ts
var import_child_process = require("child_process");
function runKotonoha(options) {
  const useStdin = options.stdin !== void 0;
  return new Promise((resolve, reject) => {
    const child = (0, import_child_process.spawn)(options.bin, options.args, {
      cwd: options.cwd,
      env: { ...process.env, ...options.env },
      stdio: useStdin ? ["pipe", "pipe", "pipe"] : ["ignore", "pipe", "pipe"]
    });
    let stdout = "";
    let stderr = "";
    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    if (useStdin && child.stdin) {
      child.stdin.write(options.stdin);
      child.stdin.end();
    }
    child.on("error", (err) => {
      reject(err);
    });
    child.on("close", (code, signal) => {
      if (signal) {
        reject(new Error(`kotonoha terminated by signal ${signal}`));
        return;
      }
      resolve({ stdout, stderr, exitCode: code ?? 1 });
    });
  });
}
function cliErrorMessage(result) {
  const err = result.stderr.trim();
  if (err) return err;
  switch (result.exitCode) {
    case 1:
      return "CLI usage or environment error (exit 1)";
    case 2:
      return "CLI validation or capability deny (exit 2)";
    case 3:
      return "CLI database or I/O error (exit 3)";
    default:
      return `kotonoha exited with code ${result.exitCode}`;
  }
}

// src/cli/buildCliEnv.ts
function buildCliEnv(settings) {
  const env = {};
  if (settings.databaseUrl?.trim()) {
    env.DATABASE_URL = settings.databaseUrl.trim();
  }
  if (settings.principalId?.trim()) {
    env.KOTONOHA_PRINCIPAL_ID = settings.principalId.trim();
  }
  if (settings.projectId?.trim()) {
    env.KOTONOHA_PROJECT_ID = settings.projectId.trim();
  }
  return env;
}

// src/util/vaultPath.ts
function vaultBasePath(app) {
  const adapter = app.vault.adapter;
  return typeof adapter.getBasePath === "function" ? adapter.getBasePath() : "";
}

// src/settings/PluginSettings.ts
var DEFAULT_SETTINGS = {
  backendMode: "mock",
  defaultLanguage: "ja",
  requireHumanApproval: true,
  preserveFrontmatter: true,
  auditLogMode: "summary",
  enableRdeAudit: true,
  gitMode: "off",
  sidecarMode: true,
  cliCommand: "kotonoha"
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var KotonohaSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Kotonoha Console" });
    new import_obsidian.Setting(containerEl).setName("Backend mode").setDesc("cli = kotonoha CLI; RDE audit works without Git; context export only when gitMode \u2260 off").addDropdown(
      (d) => d.addOptions({ mock: "mock", http: "http", cli: "cli" }).setValue(this.plugin.settings.backendMode).onChange(async (v) => {
        this.plugin.settings.backendMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "CLI (kotonoha \u2265 0.3.1)" });
    new import_obsidian.Setting(containerEl).setName("CLI command").setDesc("Path to kotonoha binary").addText(
      (t) => t.setPlaceholder("kotonoha").setValue(this.plugin.settings.cliCommand ?? "kotonoha").onChange(async (v) => {
        this.plugin.settings.cliCommand = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    ).addButton(
      (b) => b.setButtonText("Test version").onClick(() => {
        void this.plugin.testCliVersion();
      })
    );
    new import_obsidian.Setting(containerEl).setName("CLI workdir").setDesc("Git repo root for --path (empty = vault folder)").addText(
      (t) => t.setPlaceholder("(vault path)").setValue(this.plugin.settings.cliWorkdir ?? "").onChange(async (v) => {
        this.plugin.settings.cliWorkdir = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("DATABASE_URL").setDesc("Optional; required for DB-backed CLI commands later").addText(
      (t) => t.setPlaceholder("postgres://\u2026").setValue(this.plugin.settings.databaseUrl ?? "").onChange(async (v) => {
        this.plugin.settings.databaseUrl = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("KOTONOHA_PRINCIPAL_ID").addText(
      (t) => t.setPlaceholder("UUID").setValue(this.plugin.settings.principalId ?? "").onChange(async (v) => {
        this.plugin.settings.principalId = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("KOTONOHA_PROJECT_ID").addText(
      (t) => t.setPlaceholder("UUID").setValue(this.plugin.settings.projectId ?? "").onChange(async (v) => {
        this.plugin.settings.projectId = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Git mode").setDesc("Git-aware but never mutates the repo (git-mode-spec)").addDropdown(
      (d) => d.addOptions({
        off: "off",
        external: "external",
        "passive-observing": "passive-observing",
        "obsidian-git-aware": "obsidian-git-aware"
      }).setValue(this.plugin.settings.gitMode).onChange(async (v) => {
        this.plugin.settings.gitMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshNoteReader();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default language").addDropdown(
      (d) => d.addOptions({ ja: "ja", en: "en" }).setValue(this.plugin.settings.defaultLanguage).onChange(async (v) => {
        this.plugin.settings.defaultLanguage = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Require human approval before apply").addToggle(
      (t) => t.setValue(this.plugin.settings.requireHumanApproval).onChange(async (v) => {
        this.plugin.settings.requireHumanApproval = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable RDE audit panel").addToggle(
      (t) => t.setValue(this.plugin.settings.enableRdeAudit).onChange(async (v) => {
        this.plugin.settings.enableRdeAudit = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Audit log mode").addDropdown(
      (d) => d.addOptions({
        hash_only: "hash_only",
        summary: "summary",
        full_text: "full_text"
      }).setValue(this.plugin.settings.auditLogMode).onChange(async (v) => {
        this.plugin.settings.auditLogMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshAuditLog();
      })
    );
  }
};

// src/ui/KotonohaConsoleView.ts
var import_obsidian2 = require("obsidian");

// src/ui/rdeAuditPolicyMessages.ts
var RDE_AUDIT_UNAVAILABLE = "RDE audit is not available for this proposal. Review carefully before applying.";
var RDE_AUDIT_LOW_CONFIDENCE = "RDE audit confidence is low. Human review is required.";
var LOW_CONFIDENCE_THRESHOLD = 0.55;
function shouldShowLowConfidenceWarning(audit) {
  return audit.confidence < LOW_CONFIDENCE_THRESHOLD || audit.recommendedDecision === "human_review";
}

// src/ui/ProposalView.ts
var ProposalView = class {
  constructor(host, proposal, actions) {
    host.createEl("h3", {
      text: actions.auditReportOnly ? "RDE \u76E3\u67FB\u30EC\u30DD\u30FC\u30C8" : "Proposal"
    });
    if (proposal.summary) {
      host.createEl("p", { cls: "kotonoha-console-muted", text: proposal.summary });
    }
    if (actions.auditMissing) {
      host.createEl("p", { cls: "kotonoha-console-warn", text: RDE_AUDIT_UNAVAILABLE });
    }
    if (proposal.uncertaintyNote) {
      host.createEl("p", {
        cls: "kotonoha-console-warn",
        text: proposal.uncertaintyNote
      });
    }
    const pre = host.createEl("pre", { cls: "kotonoha-console-pre" });
    pre.setText(proposal.proposedText);
    const bar = host.createDiv({ cls: "kotonoha-console-actions" });
    if (!actions.auditReportOnly) {
      bar.createEl("button", { text: "Apply" }).addEventListener("click", actions.onApply);
    }
    bar.createEl("button", { text: actions.auditReportOnly ? "\u8A18\u9332\u3092\u9589\u3058\u308B" : "Reject" }).addEventListener("click", actions.onReject);
    bar.createEl("button", { text: "Copy" }).addEventListener("click", actions.onCopy);
  }
};

// src/ui/RdeAuditView.ts
var RdeAuditView = class {
  constructor(host, audit) {
    host.createEl("h3", { text: "RDE audit" });
    if (shouldShowLowConfidenceWarning(audit)) {
      host.createEl("p", { cls: "kotonoha-console-warn", text: RDE_AUDIT_LOW_CONFIDENCE });
    }
    host.createEl("p", {
      text: `Recommended: ${audit.recommendedDecision} \xB7 confidence ${(audit.confidence * 100).toFixed(0)}% (informative \u2014 not safety score)`
    });
    const cats = host.createEl("p", {
      text: `Categories: ${audit.categories.join(", ")}`
    });
    cats.addClass("kotonoha-console-muted");
    appendList(host, "Preserved", audit.preservedElements);
    appendList(host, "Transformed", audit.transformedElements);
    appendList(host, "Inferred", audit.inferredExtensions);
    appendList(host, "Unresolved", audit.unresolvedElements);
    appendList(host, "Drift risks", audit.driftRisks);
  }
};
function appendList(host, title, items) {
  if (items.length === 0) return;
  const section = host.createEl("div");
  section.createEl("strong", { text: title });
  const ul = section.createEl("ul");
  for (const item of items) {
    ul.createEl("li", { text: item });
  }
}

// src/ui/KotonohaConsoleView.ts
var KOTONOHA_CONSOLE_VIEW = "kotonoha-console-view";
var KotonohaConsoleView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  bundle = null;
  lastOperation = "rde_audit";
  sourceHashAtGeneration = null;
  proposalHost;
  auditHost;
  instructionInput;
  operationSelect;
  getViewType() {
    return KOTONOHA_CONSOLE_VIEW;
  }
  getDisplayText() {
    return "Kotonoha Console";
  }
  getIcon() {
    return "layers";
  }
  async onOpen() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("kotonoha-console-root");
    containerEl.createEl("h2", { text: "Kotonoha Console" });
    containerEl.createEl("p", {
      cls: "kotonoha-console-muted",
      text: "\u63D0\u6848\u306F\u81EA\u52D5\u9069\u7528\u3055\u308C\u307E\u305B\u3093\u3002RDE \u76E3\u67FB\u30EC\u30DD\u30FC\u30C8\u306F\u30CE\u30FC\u30C8\u306B\u66F8\u304D\u8FBC\u307F\u307E\u305B\u3093\u3002"
    });
    const ctx = await this.plugin.noteContext.capture();
    if (ctx) {
      const meta = containerEl.createEl("div", { cls: "kotonoha-console-meta" });
      meta.createEl("div", { text: `Note: ${ctx.filePath}` });
      meta.createEl("div", { text: `Source hash: ${ctx.sourceHash.slice(0, 16)}\u2026` });
      if (ctx.selectionText) {
        meta.createEl("div", { text: "Scope: selection" });
      }
      if (ctx.git) {
        meta.createEl("div", {
          text: `Git mode: ${this.plugin.settings.gitMode} \xB7 ${ctx.git.repoRelativePath}`
        });
      }
    } else {
      containerEl.createEl("p", {
        cls: "kotonoha-console-warn",
        text: "\u30A2\u30AF\u30C6\u30A3\u30D6\u306A Markdown \u30CE\u30FC\u30C8\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002"
      });
    }
    const form = containerEl.createDiv({ cls: "kotonoha-console-form" });
    form.createEl("label", { text: "Operation" });
    this.operationSelect = form.createEl("select");
    for (const op of ["rde_audit", "summarize", "rewrite", "expand", "custom"]) {
      const opt = this.operationSelect.createEl("option", { value: op, text: op });
      opt.value = op;
    }
    this.operationSelect.value = "rde_audit";
    form.createEl("label", { text: "Instruction" });
    this.instructionInput = form.createEl("textarea", {
      attr: { rows: "3", placeholder: "\u4EFB\u610F\u306E\u6307\u793A\uFF08\u76E3\u67FB\u306E\u89B3\u70B9\u306A\u3069\uFF09\u2026" }
    });
    const actions = form.createDiv({ cls: "kotonoha-console-actions" });
    actions.createEl("button", { text: "RDE \u76E3\u67FB\u3092\u5B9F\u65BD", cls: "mod-cta" }).addEventListener("click", () => void this.runRdeAudit());
    actions.createEl("button", { text: "Generate proposal" }).addEventListener(
      "click",
      () => void this.runGenerate()
    );
    this.proposalHost = containerEl.createDiv({ cls: "kotonoha-console-proposal" });
    this.auditHost = containerEl.createDiv({ cls: "kotonoha-console-audit" });
  }
  async onClose() {
    this.containerEl.empty();
  }
  /** Command palette: RDE 監査を実施 */
  async runRdeAudit() {
    this.operationSelect.value = "rde_audit";
    await this.runGenerate();
  }
  async runGenerate() {
    const ctx = await this.plugin.noteContext.capture();
    if (!ctx) {
      new import_obsidian2.Notice("\u30A2\u30AF\u30C6\u30A3\u30D6\u306A\u30CE\u30FC\u30C8\u304C\u3042\u308A\u307E\u305B\u3093");
      return;
    }
    const operation = this.operationSelect.value;
    this.lastOperation = operation;
    const instruction = this.instructionInput.value.trim();
    const request = this.plugin.generationRequests.create(
      ctx,
      operation,
      instruction,
      this.plugin.settings.defaultLanguage
    );
    try {
      this.sourceHashAtGeneration = ctx.sourceHash;
      this.bundle = await this.plugin.proposals.generate(request);
      await this.plugin.auditLog.logProposal(
        this.bundle.proposal,
        ctx.sourceText
      );
      if (this.plugin.settings.sidecarMode && this.bundle.audit) {
        await this.plugin.sidecar.saveProposalRecord(request, this.bundle.proposal);
        await this.plugin.sidecar.saveRdeAuditRecord(
          request,
          this.bundle.proposal,
          this.bundle.audit
        );
      }
      this.renderBundle();
      const msg = operation === "rde_audit" ? "RDE \u76E3\u67FB\u5B8C\u4E86\uFF08.kotonoha/audit/ \u306B\u4FDD\u5B58\uFF09" : "Proposal ready (not applied)";
      new import_obsidian2.Notice(msg);
    } catch (e) {
      new import_obsidian2.Notice(`\u5931\u6557: ${message(e)}`);
    }
  }
  renderBundle() {
    this.proposalHost.empty();
    this.auditHost.empty();
    if (!this.bundle) return;
    const isAuditReport = this.lastOperation === "rde_audit";
    const wantsAudit = this.plugin.settings.enableRdeAudit || isAuditReport;
    const auditMissing = wantsAudit && !isAuditReport && !this.bundle.audit;
    new ProposalView(this.proposalHost, this.bundle.proposal, {
      onApply: () => void this.applyProposal(),
      onReject: () => void this.rejectProposal(),
      onCopy: () => void this.copyProposal(),
      auditReportOnly: isAuditReport,
      auditMissing
    });
    if (this.bundle.audit && wantsAudit) {
      new RdeAuditView(this.auditHost, this.bundle.audit);
    }
  }
  async applyProposal() {
    if (!this.bundle) return;
    if (this.lastOperation === "rde_audit") {
      new import_obsidian2.Notice("RDE \u76E3\u67FB\u30EC\u30DD\u30FC\u30C8\u306F\u30CE\u30FC\u30C8\u306B\u9069\u7528\u3067\u304D\u307E\u305B\u3093\uFF08Copy \u3092\u4F7F\u7528\uFF09");
      return;
    }
    const ctx = await this.plugin.noteContext.capture();
    if (!ctx) {
      new import_obsidian2.Notice("No active note");
      return;
    }
    const current = await this.plugin.noteContext.capture();
    if (this.sourceHashAtGeneration && current && current.sourceHash !== this.sourceHashAtGeneration) {
      const ok = confirm(
        "\u30BD\u30FC\u30B9\u304C\u5909\u66F4\u3055\u308C\u3066\u3044\u307E\u3059\u3002\u518D\u76E3\u67FB\u307E\u305F\u306F\u660E\u793A\u7684\u306A\u4E0A\u66F8\u304D\u304C\u5FC5\u8981\u3067\u3059\u3002\u7D9A\u884C\u3057\u307E\u3059\u304B\uFF1F"
      );
      if (!ok) return;
    }
    if (this.plugin.settings.requireHumanApproval) {
      const ok = confirm(
        "\u3053\u306E\u63D0\u6848\u3092\u30CE\u30FC\u30C8\u306B\u9069\u7528\u3057\u307E\u3059\u304B\uFF1F\u5143\u306E\u30C6\u30AD\u30B9\u30C8\u306F\u4E0A\u66F8\u304D\u3055\u308C\u307E\u3059\u3002"
      );
      if (!ok) return;
    }
    const file = this.plugin.activeNoteReader.getActiveFile();
    if (!file) return;
    const text = this.bundle.proposal.proposedText;
    if (ctx.selectionText) {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      const editor = view?.editor;
      if (editor) {
        editor.replaceSelection(text);
      } else {
        new import_obsidian2.Notice("Open note in editor to apply selection");
        return;
      }
    } else {
      await this.plugin.markdownWriter.replaceNoteContent(file, text);
    }
    const decision = this.plugin.approval.approve(this.bundle.proposal, text);
    await this.plugin.auditLog.logDecision(decision, this.bundle.audit);
    new import_obsidian2.Notice("Applied (audit logged)");
    this.bundle = null;
    this.proposalHost.empty();
    this.auditHost.empty();
  }
  async rejectProposal() {
    if (!this.bundle) return;
    const decision = this.plugin.approval.reject(this.bundle.proposal);
    await this.plugin.auditLog.logDecision(decision, this.bundle.audit);
    new import_obsidian2.Notice(this.lastOperation === "rde_audit" ? "\u76E3\u67FB\u3092\u8A18\u9332\uFF08\u5374\u4E0B\uFF09" : "Rejected");
    this.bundle = null;
    this.proposalHost.empty();
    this.auditHost.empty();
  }
  async copyProposal() {
    if (!this.bundle) return;
    await navigator.clipboard.writeText(this.bundle.proposal.proposedText);
    new import_obsidian2.Notice("\u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F");
  }
};
function message(e) {
  return e instanceof Error ? e.message : String(e);
}

// src/util/hash.ts
async function sha256Hex(text) {
  const data = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// src/obsidian/GitContextReader.ts
async function readGitContext(app, file, mode) {
  if (mode === "off") return void 0;
  const repoRelativePath = file.path;
  const dirty = app.vault.getAbstractFileByPath(file.path) !== null;
  return {
    repoRelativePath,
    dirty,
    branch: mode === "passive-observing" ? void 0 : void 0,
    commit: void 0,
    root: vaultBasePath(app) || void 0
  };
}

// src/obsidian/ActiveNoteReader.ts
var ActiveNoteReader = class {
  constructor(app, gitMode) {
    this.app = app;
    this.gitMode = gitMode;
  }
  getActiveFile() {
    const file = this.app.workspace.getActiveFile();
    return file ?? null;
  }
  async readNoteContext(selectionText) {
    const file = this.getActiveFile();
    if (!file) return null;
    const sourceText = await this.app.vault.read(file);
    const targetText = selectionText !== void 0 && selectionText.length > 0 ? selectionText : sourceText;
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache?.frontmatter ?? {};
    const tags = (cache?.tags ?? []).map((t) => t.tag);
    const links = (cache?.links ?? []).map((l) => l.link);
    const git = this.gitMode === "off" ? void 0 : await readGitContext(this.app, file, this.gitMode);
    return {
      vaultPath: vaultBasePath(this.app),
      filePath: file.path,
      title: file.basename,
      sourceText: targetText,
      selectionText: selectionText && selectionText.length > 0 ? selectionText : void 0,
      sourceHash: await sha256Hex(targetText),
      tags,
      links,
      frontmatter,
      git
    };
  }
};

// src/obsidian/MarkdownWriter.ts
var MarkdownWriter = class {
  constructor(app) {
    this.app = app;
  }
  async replaceNoteContent(file, newContent) {
    await this.app.vault.modify(file, newContent);
  }
};

// src/services/NoteContextService.ts
var NoteContextService = class {
  constructor(reader) {
    this.reader = reader;
  }
  async capture(selectionText) {
    return this.reader.readNoteContext(selectionText);
  }
};

// src/services/GenerationRequestService.ts
var GenerationRequestService = class {
  create(context, operation, instruction, language) {
    return {
      id: crypto.randomUUID(),
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      operation,
      instruction,
      context,
      language
    };
  }
};

// src/services/ProposalService.ts
var ProposalService = class {
  constructor(client) {
    this.client = client;
  }
  async generate(request) {
    const result = await this.client.generate(request);
    return { proposal: result.proposal, audit: result.audit };
  }
};

// src/services/ApprovalService.ts
var ApprovalService = class {
  approve(proposal, appliedText, comment) {
    return {
      proposalId: proposal.id,
      decidedAt: (/* @__PURE__ */ new Date()).toISOString(),
      decision: "approved",
      appliedText,
      comment
    };
  }
  reject(proposal, comment) {
    return {
      proposalId: proposal.id,
      decidedAt: (/* @__PURE__ */ new Date()).toISOString(),
      decision: "rejected",
      comment
    };
  }
};

// src/services/AuditLogService.ts
var KOTONOHA_DIR = ".kotonoha/audit";
var AuditLogService = class {
  constructor(app, mode) {
    this.app = app;
    this.mode = mode;
  }
  async logProposal(proposal, sourceExcerpt) {
    const entry = {
      kind: "proposal",
      proposalId: proposal.id,
      createdAt: proposal.createdAt,
      proposalHash: await sha256Hex(proposal.proposedText),
      sourceExcerpt: excerpt(sourceExcerpt, this.mode),
      summary: proposal.summary
    };
    await this.append(entry);
  }
  async logDecision(decision, audit) {
    const entry = {
      kind: "decision",
      ...decision,
      rdeCategories: audit?.categories
    };
    await this.append(entry);
  }
  async append(entry) {
    const name = `${isoFileStamp()}.json`;
    const path = `${KOTONOHA_DIR}/${name}`;
    await this.ensureDir();
    const line = JSON.stringify(entry, null, 2);
    await this.app.vault.adapter.write(path, line);
  }
  async ensureDir() {
    const adapter = this.app.vault.adapter;
    if (!await adapter.exists(KOTONOHA_DIR)) {
      await adapter.mkdir(KOTONOHA_DIR);
    }
  }
};
function isoFileStamp() {
  return (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
}
function excerpt(text, mode) {
  if (mode === "hash_only") return "";
  const max = mode === "summary" ? 200 : 4e3;
  return text.length <= max ? text : `${text.slice(0, max)}\u2026`;
}

// src/services/SidecarStore.ts
var ROOT = ".kotonoha";
var PROPOSALS = `${ROOT}/proposals`;
var AUDIT = `${ROOT}/audit`;
var SidecarStore = class {
  constructor(app) {
    this.app = app;
  }
  async saveProposalRecord(request, proposal) {
    await this.ensureDirs();
    const path = `${PROPOSALS}/${proposal.id}.proposal.json`;
    const body = {
      format: "kotonoha.obsidian.proposal.v0.1",
      proposalId: proposal.id,
      requestId: request.id,
      operation: request.operation,
      filePath: request.context.filePath,
      sourceHash: request.context.sourceHash,
      proposalHash: await hash(proposal.proposedText),
      createdAt: proposal.createdAt,
      summary: proposal.summary
    };
    await this.app.vault.adapter.write(path, JSON.stringify(body, null, 2));
  }
  async saveRdeAuditRecord(request, proposal, audit) {
    await this.ensureDirs();
    const path = `${AUDIT}/${proposal.id}.rde-audit.json`;
    const body = {
      format: "kotonoha.obsidian.rde_audit.v0.1",
      proposalId: proposal.id,
      filePath: request.context.filePath,
      sourceHash: request.context.sourceHash,
      operation: request.operation,
      createdAt: audit.createdAt,
      audit
    };
    await this.app.vault.adapter.write(path, JSON.stringify(body, null, 2));
  }
  async ensureDirs() {
    const adapter = this.app.vault.adapter;
    for (const dir of [ROOT, PROPOSALS, AUDIT]) {
      if (!await adapter.exists(dir)) {
        await adapter.mkdir(dir);
      }
    }
  }
};
async function hash(text) {
  const data = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// src/cli/proposalFromContextPack.ts
function parseContextPack(stdout) {
  const pack = JSON.parse(stdout);
  if (pack.format !== "kotonoha.context_pack.v0.1") {
    throw new Error(`unexpected context pack format: ${pack.format ?? "(missing)"}`);
  }
  return pack;
}
function proposalTextFromContextPack(request, pack) {
  const anchor = pack.git_anchor;
  const lines = [
    `<!-- kotonoha cli ${request.operation} -->`,
    "",
    `## Operation`,
    request.operation,
    "",
    `## Instruction`,
    request.instruction || "(none)",
    ""
  ];
  if (anchor?.git_commit) {
    lines.push(`## Git anchor`, `- commit: \`${anchor.git_commit}\``, `- file: \`${anchor.file_path ?? request.context.filePath}\``);
    if (anchor.line_range_start != null) {
      lines.push(`- lines: ${anchor.line_range_start}\u2013${anchor.line_range_end ?? anchor.line_range_start}`);
    }
    lines.push("");
  }
  lines.push("## Source", "", request.context.sourceText, "", "---", "", "*CLI mode uses `kotonoha context export` only; connect an orchestrator/LLM for generative rewrite.*");
  return lines.join("\n");
}

// src/cli/proposalFromLocal.ts
function proposalTextFromLocalContext(request) {
  const { context, operation, instruction } = request;
  return [
    `<!-- kotonoha cli-local ${operation} -->`,
    "",
    `## Operation`,
    operation,
    "",
    `## Instruction`,
    instruction || "(none)",
    "",
    `## Anchor (non-Git)`,
    `- path: \`${context.filePath}\``,
    `- source_hash: \`${context.sourceHash.slice(0, 16)}\u2026\``,
    "",
    "## Source",
    "",
    context.sourceText,
    "",
    "---",
    "",
    "*Git-aware `context export` skipped (`gitMode: off` or unavailable). Semantic anchors use path + source hash per git-mode-spec.*"
  ].join("\n");
}

// src/rde/StructuralDiffBuilder.ts
var REWRITE_LENGTH_SHRINK_RATIO = 0.5;
var HEDGING = /\b(may|might|could|possibly|perhaps|likely|probably|かもしれない|可能性|推測)\b/giu;
var STRONG = /\b(must|will|always|never|certainly|clearly|proves?|確実|必ず|明らか|証明)\b/giu;
function buildSourceReview(source) {
  const preservedElements = [];
  const unresolvedElements = [];
  const categories = /* @__PURE__ */ new Set();
  const hedgeCount = (source.match(HEDGING) ?? []).length;
  const strongCount = (source.match(STRONG) ?? []).length;
  const lineCount = source.split(/\n/).filter((l) => l.trim()).length;
  categories.add("preserved");
  preservedElements.push(`source note review (${lineCount} non-empty lines)`);
  if (hedgeCount > 0) {
    categories.add("unresolved");
    unresolvedElements.push(
      `source contains ${hedgeCount} hedging marker(s) \u2014 meaning may remain open`
    );
  }
  if (strongCount > 0) {
    preservedElements.push(`source contains ${strongCount} strong claim marker(s)`);
  }
  if (hedgeCount === 0 && strongCount === 0 && source.trim().length > 0) {
    unresolvedElements.push(
      "no hedging or strong-claim markers detected \u2014 rule-based signals limited"
    );
    categories.add("unresolved");
  }
  return {
    categories: [...categories],
    preservedElements,
    transformedElements: [],
    inferredExtensions: [],
    unresolvedElements,
    driftRisks: [],
    lineAdditions: 0,
    lineDeletions: 0
  };
}
function buildStructuralDiff(source, proposal, options) {
  const preservedElements = [];
  const transformedElements = [];
  const inferredExtensions = [];
  const unresolvedElements = [];
  const driftRisks = [];
  const categories = /* @__PURE__ */ new Set();
  const srcLines = source.split(/\n/);
  const propLines = (proposal ?? source).split(/\n/);
  const sameText = source.trim() === (proposal ?? source).trim();
  let lineAdditions = 0;
  let lineDeletions = 0;
  if (!sameText && proposal) {
    const srcSet = new Set(srcLines.map((l) => l.trim()).filter(Boolean));
    const propSet = new Set(propLines.map((l) => l.trim()).filter(Boolean));
    for (const l of propSet) {
      if (!srcSet.has(l)) lineAdditions++;
    }
    for (const l of srcSet) {
      if (!propSet.has(l)) lineDeletions++;
    }
    if (lineAdditions > 0 || lineDeletions > 0) {
      categories.add("authorized_transformation");
      transformedElements.push(
        `lines +${lineAdditions} / -${lineDeletions} (structural)`
      );
    }
  } else {
    categories.add("preserved");
    preservedElements.push("source and proposal text match (structural)");
  }
  scanClaimStrength(source, proposal ?? source, driftRisks, categories);
  scanHedgingLoss(source, proposal ?? source, driftRisks, categories);
  if (srcLines.length > 3) {
    preservedElements.push(`source paragraphs: ${srcLines.filter((l) => l.trim()).length}`);
  }
  if (driftRisks.length === 0 && !sameText && proposal) {
    const ratio = proposal.length / Math.max(source.length, 1);
    if (ratio > 1.4) {
      inferredExtensions.push(`proposal length \xD7${ratio.toFixed(2)} vs source`);
      categories.add("inferred_extension");
    }
  }
  if (!sameText && proposal) {
    scanMvpGuardrails(source, proposal, options, driftRisks, categories);
  }
  if (categories.size === 0) {
    categories.add("unresolved");
    unresolvedElements.push("insufficient structural signal for classification");
  }
  return {
    categories: [...categories],
    preservedElements,
    transformedElements,
    inferredExtensions,
    unresolvedElements,
    driftRisks,
    lineAdditions,
    lineDeletions
  };
}
function scanClaimStrength(source, proposal, driftRisks, categories) {
  const srcHedge = (source.match(HEDGING) ?? []).length;
  const propHedge = (proposal.match(HEDGING) ?? []).length;
  const srcStrong = (source.match(STRONG) ?? []).length;
  const propStrong = (proposal.match(STRONG) ?? []).length;
  if (srcHedge > 0 && propStrong > srcStrong && propHedge < srcHedge) {
    driftRisks.push("claim strength may have increased (hedging reduced, certainty markers added)");
    categories.add("suspicious_drift");
  }
  if (propStrong > 0 && srcHedge > 0 && propHedge === 0) {
    driftRisks.push("hedging removed while strong claims present in proposal");
    categories.add("suspicious_drift");
  }
}
function scanHedgingLoss(source, proposal, driftRisks, categories) {
  if (source === proposal) return;
  const lost = ["may", "might", "could", "possibly"].filter(
    (w) => source.toLowerCase().includes(w) && !proposal.toLowerCase().includes(w)
  );
  if (lost.length > 0) {
    driftRisks.push(`hedging terms dropped: ${lost.join(", ")}`);
    categories.add("suspicious_drift");
  }
}
function scanMvpGuardrails(source, proposal, options, driftRisks, categories) {
  const fm = options?.frontmatter ?? {};
  for (const key of Object.keys(fm)) {
    if (!proposal.includes(`${key}:`) && !proposal.includes(`${key} `)) {
      driftRisks.push(`frontmatter key may be removed or altered: ${key}`);
      categories.add("suspicious_drift");
    }
  }
  const linkTargets = new Set(options?.sourceLinks ?? []);
  for (const m of source.matchAll(/\[\[([^\]|#]+)/g)) {
    linkTargets.add(m[1]);
  }
  for (const m of source.matchAll(/\]\(([^)]+)\)/g)) {
    linkTargets.add(m[1]);
  }
  for (const target of linkTargets) {
    const needle = target.replace(/^\[\[/, "").replace(/\]\]$/, "");
    if (needle && !proposal.includes(needle)) {
      driftRisks.push(`link or wikilink may be removed: ${needle}`);
      categories.add("suspicious_drift");
    }
  }
  if (options?.operation === "rewrite") {
    const ratio = proposal.length / Math.max(source.length, 1);
    if (ratio < REWRITE_LENGTH_SHRINK_RATIO) {
      driftRisks.push(
        `rewrite shortened text to ${(ratio * 100).toFixed(0)}% of source (threshold ${REWRITE_LENGTH_SHRINK_RATIO * 100}%)`
      );
      categories.add("suspicious_drift");
    }
  }
}

// src/rde/mergeRdeAudit.ts
function mergeUnique(target, more) {
  for (const item of more) {
    if (!target.includes(item)) target.push(item);
  }
}
function mergeCategories(a, b) {
  return [.../* @__PURE__ */ new Set([...a, ...b])];
}
function mergeStructuralIntoAudit(base, structural) {
  const preservedElements = [...base.preservedElements];
  const transformedElements = [...base.transformedElements];
  const inferredExtensions = [...base.inferredExtensions];
  const unresolvedElements = [...base.unresolvedElements];
  const driftRisks = [...base.driftRisks];
  mergeUnique(preservedElements, structural.preservedElements);
  mergeUnique(transformedElements, structural.transformedElements);
  mergeUnique(inferredExtensions, structural.inferredExtensions);
  mergeUnique(unresolvedElements, structural.unresolvedElements);
  mergeUnique(driftRisks, structural.driftRisks);
  const categories = mergeCategories(base.categories, structural.categories);
  const recommendedDecision = recommendDecision(categories, driftRisks);
  return {
    ...base,
    categories,
    preservedElements,
    transformedElements,
    inferredExtensions,
    unresolvedElements,
    driftRisks,
    recommendedDecision,
    confidence: driftRisks.length > 0 ? 0.45 : structural.lineAdditions > 0 ? 0.65 : 0.75
  };
}
function recommendDecision(categories, driftRisks) {
  if (categories.includes("critical_distortion")) return "reject";
  if (driftRisks.length >= 2 || categories.includes("suspicious_drift")) {
    return "revise";
  }
  if (categories.includes("unresolved") && categories.length <= 1) {
    return "human_review";
  }
  if (categories.includes("preserved") && driftRisks.length === 0) {
    return "approve";
  }
  return "human_review";
}

// src/rde/enrichAuditFromSource.ts
function enrichAuditFromSource(audit, request) {
  const excerpt2 = request.context.sourceText.slice(0, 200).replace(/\n/g, " ") + (request.context.sourceText.length > 200 ? "\u2026" : "");
  const unresolvedElements = [...audit.unresolvedElements];
  if (!request.context.git) {
    unresolvedElements.push(
      "Non-Git vault: no commit boundary; semantic anchors use path + source_hash only"
    );
  }
  return {
    ...audit,
    preservedElements: [
      `path:${request.context.filePath}`,
      `source_hash:${request.context.sourceHash.slice(0, 16)}\u2026`,
      excerpt2,
      ...audit.preservedElements
    ],
    unresolvedElements
  };
}

// src/rde/parseRdeEmit.ts
var CATEGORY_MAP = {
  preserved: "preserved",
  complemented: "inferred_extension",
  transformed: "authorized_transformation",
  deviation_risk: "suspicious_drift",
  intentionally_unresolved: "unresolved",
  lost: "critical_distortion",
  next_update_policy: "unresolved"
};
function rdeAuditFromEmit(stdout, proposalId) {
  const root = JSON.parse(stdout);
  const cats = root.rde_review_output?.categories ?? {};
  const categories = /* @__PURE__ */ new Set();
  const preservedElements = [];
  const transformedElements = [];
  const inferredExtensions = [];
  const unresolvedElements = [];
  const driftRisks = [];
  for (const [key, items] of Object.entries(cats)) {
    const mapped = CATEGORY_MAP[key];
    if (mapped) categories.add(mapped);
    const target = key === "preserved" ? preservedElements : key === "transformed" ? transformedElements : key === "complemented" ? inferredExtensions : key === "deviation_risk" ? driftRisks : unresolvedElements;
    for (const item of items ?? []) {
      target.push(String(item));
    }
  }
  if (categories.size === 0) {
    categories.add("unresolved");
  }
  return {
    proposalId,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    categories: [...categories],
    preservedElements,
    transformedElements,
    inferredExtensions,
    unresolvedElements,
    driftRisks,
    recommendedDecision: "human_review",
    confidence: 0.5
  };
}

// src/services/RdeAuditService.ts
function performRdeAudit(request, proposalId, options) {
  const structural = options?.sourceReview && !options?.proposalText ? buildSourceReview(request.context.sourceText) : buildStructuralDiff(
    request.context.sourceText,
    options?.proposalText ?? request.context.sourceText,
    {
      operation: request.operation,
      frontmatter: request.context.frontmatter,
      sourceLinks: request.context.links
    }
  );
  let base;
  if (options?.cli?.emitStdout) {
    base = rdeAuditFromEmit(options.cli.emitStdout, proposalId);
  } else {
    base = {
      proposalId,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      categories: [],
      preservedElements: [],
      transformedElements: [],
      inferredExtensions: [],
      unresolvedElements: [],
      driftRisks: [],
      recommendedDecision: "human_review",
      confidence: 0.5
    };
  }
  const merged = mergeStructuralIntoAudit(base, structural);
  return enrichAuditFromSource(merged, request);
}

// src/rde/rdeAuditReport.ts
function rdeAuditReportMarkdown(request, audit) {
  const lines = [
    `<!-- kotonoha rde-audit -->`,
    "",
    `# RDE audit`,
    "",
    `**File:** \`${request.context.filePath}\``,
    `**Source hash:** \`${request.context.sourceHash.slice(0, 16)}\u2026\``,
    `**Recommended:** ${audit.recommendedDecision}`,
    "",
    "## Categories",
    audit.categories.join(", ") || "(none)",
    ""
  ];
  appendSection(lines, "Preserved", audit.preservedElements);
  appendSection(lines, "Transformed", audit.transformedElements);
  appendSection(lines, "Inferred", audit.inferredExtensions);
  appendSection(lines, "Unresolved", audit.unresolvedElements);
  appendSection(lines, "Drift risks", audit.driftRisks);
  lines.push("## Source excerpt", "", request.context.sourceText.slice(0, 2e3));
  if (request.context.sourceText.length > 2e3) {
    lines.push("", "\u2026");
  }
  return lines.join("\n");
}
function appendSection(lines, title, items) {
  if (items.length === 0) return;
  lines.push(`## ${title}`, "");
  for (const item of items) {
    lines.push(`- ${item}`);
  }
  lines.push("");
}

// src/client/CliKotonohaClient.ts
var CliKotonohaClient = class {
  constructor(options) {
    this.options = options;
    this.runner = options.runner ?? runKotonoha;
  }
  runner;
  async generate(request) {
    await this.assertCliAvailable();
    const proposalId = crypto.randomUUID();
    if (request.operation === "rde_audit") {
      return this.generateRdeAudit(request, proposalId);
    }
    if (this.mayUseContextExport()) {
      try {
        return await this.generateWithContextExport(request, proposalId);
      } catch (e) {
        const fallback = this.generateLocal(request, proposalId);
        fallback.proposal.uncertaintyNote = [
          fallback.proposal.uncertaintyNote,
          "Git-aware context export failed; using path + source_hash anchors.",
          e instanceof Error ? e.message : String(e)
        ].join(" ");
        return fallback;
      }
    }
    return this.generateLocal(request, proposalId);
  }
  /** git-mode-spec §10: non-Git mode must not require Git-aware CLI. */
  mayUseContextExport() {
    return this.options.gitMode !== "off";
  }
  async generateRdeAudit(request, proposalId) {
    const emitResult = await this.run({ args: ["rde", "emit"] });
    if (emitResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(emitResult));
    }
    const validateResult = await this.run({
      args: ["rde", "validate", "--strict"],
      stdin: emitResult.stdout
    });
    if (validateResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(validateResult));
    }
    const audit = performRdeAudit(request, proposalId, {
      cli: { emitStdout: emitResult.stdout },
      sourceReview: true
    });
    const proposedText = rdeAuditReportMarkdown(request, audit);
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText,
        summary: `[cli] RDE audit \xB7 ${request.context.filePath}`,
        uncertaintyNote: "Rule-based source review + CLI `rde emit`/`validate` (interchange skeleton only \u2014 not full RDE). DB attach when DATABASE_URL is configured."
      },
      audit
    };
  }
  async generateWithContextExport(request, proposalId) {
    const relFile = request.context.filePath;
    const args = ["context", "export", relFile, "--path", this.options.cwd];
    const obsPath = await this.maybeObservationPath(request);
    if (obsPath) args.push("--observation", obsPath);
    const packResult = await this.run({ args });
    if (packResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(packResult));
    }
    const pack = parseContextPack(packResult.stdout);
    const proposedText = proposalTextFromContextPack(request, pack);
    return this.withLocalAudit(request, proposalId, proposedText, {
      summary: `[cli] context export \xB7 ${request.operation} \xB7 ${relFile}`,
      uncertaintyNote: "Generative rewrite requires an orchestrator/LLM; proposal embeds `kotonoha context export`. Local rule-based RDE audit attached."
    });
  }
  generateLocal(request, proposalId) {
    const proposedText = proposalTextFromLocalContext(request);
    return this.withLocalAudit(request, proposalId, proposedText, {
      summary: `[cli-local] ${request.operation} \xB7 ${request.context.filePath}`,
      uncertaintyNote: this.options.gitMode === "off" ? "gitMode is off \u2014 Git-aware CLI not used (git-mode-spec \xA74). Local rule-based RDE audit attached." : "Local anchors only (path + source_hash). Local rule-based RDE audit attached."
    });
  }
  withLocalAudit(request, proposalId, proposedText, meta) {
    const audit = performRdeAudit(request, proposalId, { proposalText: proposedText });
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText,
        summary: meta.summary,
        uncertaintyNote: meta.uncertaintyNote
      },
      audit
    };
  }
  async assertCliAvailable() {
    const result = await this.run({ args: ["version"] });
    if (result.exitCode !== 0) {
      throw new Error(
        `kotonoha not available (${this.options.bin}): ${cliErrorMessage(result)}`
      );
    }
  }
  async maybeObservationPath(request) {
    if (!this.options.writeObservation) return void 0;
    const hasInstruction = request.instruction.trim().length > 0;
    if (!hasInstruction && request.operation === "custom") return void 0;
    return this.options.writeObservation({
      operation: request.operation,
      instruction: request.instruction,
      source_hash: request.context.sourceHash
    });
  }
  run(partial) {
    return this.runner({
      bin: this.options.bin,
      cwd: this.options.cwd,
      env: this.options.env,
      args: partial.args,
      stdin: partial.stdin
    });
  }
};

// src/client/MockKotonohaClient.ts
function id() {
  return crypto.randomUUID();
}
var MockKotonohaClient = class {
  async generate(request) {
    const { context, operation, instruction } = request;
    const excerpt2 = context.sourceText.slice(0, 120).replace(/\n/g, " ") + (context.sourceText.length > 120 ? "\u2026" : "");
    const proposedText = [
      `<!-- kotonoha mock ${operation} -->`,
      "",
      `> ${instruction || "(no instruction)"}`,
      "",
      context.sourceText
    ].join("\n");
    const proposalId = id();
    if (operation === "rde_audit") {
      const audit2 = performRdeAudit(request, proposalId, { sourceReview: true });
      return {
        proposal: {
          id: proposalId,
          requestId: request.id,
          createdAt: (/* @__PURE__ */ new Date()).toISOString(),
          proposedText: rdeAuditReportMarkdown(request, audit2),
          summary: `[mock] RDE audit \xB7 ${context.title}`
        },
        audit: audit2
      };
    }
    const mockProposal = proposedText;
    const audit = performRdeAudit(request, proposalId, {
      proposalText: mockProposal
    });
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText: mockProposal,
        summary: `[mock] ${operation} on ${context.title}`,
        uncertaintyNote: "Mock backend \u2014 connect HTTP or CLI in settings for real Kotonoha output."
      },
      audit
    };
  }
};

// src/client/createClient.ts
var OBSERVATION_REL = ".kotonoha/cli-observation.json";
function createKotonohaClient(settings, app) {
  switch (settings.backendMode) {
    case "cli": {
      const cwd = settings.cliWorkdir?.trim() || vaultBasePath(app) || process.cwd();
      return new CliKotonohaClient({
        bin: settings.cliCommand?.trim() || "kotonoha",
        cwd,
        gitMode: settings.gitMode,
        env: buildCliEnv(settings),
        writeObservation: async (payload) => {
          const dir = ".kotonoha";
          const adapter = app.vault.adapter;
          if (!await adapter.exists(dir)) {
            await adapter.mkdir(dir);
          }
          await adapter.write(
            OBSERVATION_REL,
            JSON.stringify(payload, null, 2)
          );
          return OBSERVATION_REL;
        }
      });
    }
    case "mock":
      return new MockKotonohaClient();
    case "http":
      return new MockKotonohaClient();
    default:
      return new MockKotonohaClient();
  }
}

// src/main.ts
var KotonohaConsolePlugin = class extends import_obsidian3.Plugin {
  settings = { ...DEFAULT_SETTINGS };
  activeNoteReader;
  markdownWriter;
  noteContext;
  generationRequests = new GenerationRequestService();
  proposals;
  approval = new ApprovalService();
  auditLog;
  sidecar;
  client;
  async onload() {
    await this.loadSettings();
    this.refreshNoteReader();
    this.markdownWriter = new MarkdownWriter(this.app);
    this.noteContext = new NoteContextService(this.activeNoteReader);
    this.refreshClient();
    this.refreshAuditLog();
    this.sidecar = new SidecarStore(this.app);
    this.registerView(KOTONOHA_CONSOLE_VIEW, (leaf) => new KotonohaConsoleView(leaf, this));
    this.addRibbonIcon("layers", "Kotonoha Console", () => {
      void this.activateConsole();
    });
    this.addCommand({
      id: "open-console",
      name: "Open Kotonoha Console",
      callback: () => void this.activateConsole()
    });
    this.addCommand({
      id: "run-rde-audit",
      name: "RDE \u76E3\u67FB\u3092\u5B9F\u65BD\uFF08\u30A2\u30AF\u30C6\u30A3\u30D6\u30CE\u30FC\u30C8\uFF09",
      callback: () => void this.runRdeAuditCommand()
    });
    this.addSettingTab(new KotonohaSettingsTab(this.app, this));
  }
  refreshNoteReader() {
    this.activeNoteReader = new ActiveNoteReader(this.app, this.settings.gitMode);
  }
  refreshClient() {
    this.client = createKotonohaClient(this.settings, this.app);
    this.proposals = new ProposalService(this.client);
  }
  refreshAuditLog() {
    this.auditLog = new AuditLogService(this.app, this.settings.auditLogMode);
  }
  async runRdeAuditCommand() {
    await this.activateConsole();
    const leaves = this.app.workspace.getLeavesOfType(KOTONOHA_CONSOLE_VIEW);
    const view = leaves[0]?.view;
    if (view && "runRdeAudit" in view && typeof view.runRdeAudit === "function") {
      await view.runRdeAudit();
    }
  }
  async activateConsole() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(KOTONOHA_CONSOLE_VIEW)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right) return;
      await right.setViewState({ type: KOTONOHA_CONSOLE_VIEW, active: true });
      leaf = right;
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...await this.loadData()
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async testCliVersion() {
    const bin = this.settings.cliCommand?.trim() || "kotonoha";
    const cwd = this.settings.cliWorkdir?.trim() || vaultBasePath(this.app) || ".";
    try {
      const result = await runKotonoha({
        bin,
        cwd,
        args: ["version"],
        env: buildCliEnv(this.settings)
      });
      if (result.exitCode === 0) {
        new import_obsidian3.Notice(result.stdout.trim().split("\n")[0] ?? "kotonoha ok");
      } else {
        new import_obsidian3.Notice(`CLI error: ${cliErrorMessage(result)}`);
      }
    } catch (e) {
      new import_obsidian3.Notice(`CLI spawn failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
};
