/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KotonohaConsolePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/cli/runKotonoha.ts
var import_child_process = require("child_process");
function runKotonoha(options) {
  const useStdin = options.stdin !== void 0;
  return new Promise((resolve, reject) => {
    const child = (0, import_child_process.spawn)(options.bin, options.args, {
      cwd: options.cwd,
      env: { ...process.env, ...options.env },
      stdio: useStdin ? ["pipe", "pipe", "pipe"] : ["ignore", "pipe", "pipe"]
    });
    let stdout = "";
    let stderr = "";
    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    if (useStdin && child.stdin) {
      child.stdin.write(options.stdin);
      child.stdin.end();
    }
    child.on("error", (err) => {
      reject(err);
    });
    child.on("close", (code, signal) => {
      if (signal) {
        reject(new Error(`kotonoha terminated by signal ${signal}`));
        return;
      }
      resolve({ stdout, stderr, exitCode: code ?? 1 });
    });
  });
}
function cliErrorMessage(result) {
  const err = result.stderr.trim();
  if (err) return err;
  switch (result.exitCode) {
    case 1:
      return "CLI usage or environment error (exit 1)";
    case 2:
      return "CLI validation or capability deny (exit 2)";
    case 3:
      return "CLI database or I/O error (exit 3)";
    default:
      return `kotonoha exited with code ${result.exitCode}`;
  }
}

// src/cli/buildCliEnv.ts
function buildCliEnv(settings) {
  const env = {};
  if (settings.databaseUrl?.trim()) {
    env.DATABASE_URL = settings.databaseUrl.trim();
  }
  if (settings.principalId?.trim()) {
    env.KOTONOHA_PRINCIPAL_ID = settings.principalId.trim();
  }
  if (settings.projectId?.trim()) {
    env.KOTONOHA_PROJECT_ID = settings.projectId.trim();
  }
  return env;
}

// src/util/vaultPath.ts
function vaultBasePath(app) {
  const adapter = app.vault.adapter;
  return typeof adapter.getBasePath === "function" ? adapter.getBasePath() : "";
}

// src/settings/PluginSettings.ts
var DEFAULT_SETTINGS = {
  backendMode: "mock",
  defaultLanguage: "ja",
  requireHumanApproval: true,
  preserveFrontmatter: true,
  auditLogMode: "summary",
  enableRdeAudit: true,
  gitMode: "off",
  sidecarMode: true,
  cliCommand: "kotonoha"
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var KotonohaSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Kotonoha Console" });
    new import_obsidian.Setting(containerEl).setName("Backend mode").setDesc("cli = kotonoha CLI; RDE audit works without Git; context export only when gitMode \u2260 off").addDropdown(
      (d) => d.addOptions({ mock: "mock", http: "http", cli: "cli" }).setValue(this.plugin.settings.backendMode).onChange(async (v) => {
        this.plugin.settings.backendMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "CLI (kotonoha \u2265 0.3.1)" });
    new import_obsidian.Setting(containerEl).setName("CLI command").setDesc("Path to kotonoha binary").addText(
      (t) => t.setPlaceholder("kotonoha").setValue(this.plugin.settings.cliCommand ?? "kotonoha").onChange(async (v) => {
        this.plugin.settings.cliCommand = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    ).addButton(
      (b) => b.setButtonText("Test version").onClick(() => {
        void this.plugin.testCliVersion();
      })
    );
    new import_obsidian.Setting(containerEl).setName("CLI workdir").setDesc("Git repo root for --path (empty = vault folder)").addText(
      (t) => t.setPlaceholder("(vault path)").setValue(this.plugin.settings.cliWorkdir ?? "").onChange(async (v) => {
        this.plugin.settings.cliWorkdir = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("DATABASE_URL").setDesc("Optional; required for DB-backed CLI commands later").addText(
      (t) => t.setPlaceholder("postgres://\u2026").setValue(this.plugin.settings.databaseUrl ?? "").onChange(async (v) => {
        this.plugin.settings.databaseUrl = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("KOTONOHA_PRINCIPAL_ID").addText(
      (t) => t.setPlaceholder("UUID").setValue(this.plugin.settings.principalId ?? "").onChange(async (v) => {
        this.plugin.settings.principalId = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("KOTONOHA_PROJECT_ID").addText(
      (t) => t.setPlaceholder("UUID").setValue(this.plugin.settings.projectId ?? "").onChange(async (v) => {
        this.plugin.settings.projectId = v;
        await this.plugin.saveSettings();
        this.plugin.refreshClient();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Git mode").setDesc("Git-aware but never mutates the repo (git-mode-spec)").addDropdown(
      (d) => d.addOptions({
        off: "off",
        external: "external",
        "passive-observing": "passive-observing",
        "obsidian-git-aware": "obsidian-git-aware"
      }).setValue(this.plugin.settings.gitMode).onChange(async (v) => {
        this.plugin.settings.gitMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshNoteReader();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default language").addDropdown(
      (d) => d.addOptions({ ja: "ja", en: "en" }).setValue(this.plugin.settings.defaultLanguage).onChange(async (v) => {
        this.plugin.settings.defaultLanguage = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Require human approval before apply").addToggle(
      (t) => t.setValue(this.plugin.settings.requireHumanApproval).onChange(async (v) => {
        this.plugin.settings.requireHumanApproval = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable RDE audit panel").addToggle(
      (t) => t.setValue(this.plugin.settings.enableRdeAudit).onChange(async (v) => {
        this.plugin.settings.enableRdeAudit = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Audit log mode").addDropdown(
      (d) => d.addOptions({
        hash_only: "hash_only",
        summary: "summary",
        full_text: "full_text"
      }).setValue(this.plugin.settings.auditLogMode).onChange(async (v) => {
        this.plugin.settings.auditLogMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshAuditLog();
      })
    );
  }
};

// src/ui/KotonohaConsoleView.ts
var import_obsidian2 = require("obsidian");

// src/ui/ProposalView.ts
var ProposalView = class {
  constructor(host, proposal, actions) {
    host.createEl("h3", { text: "Proposal" });
    if (proposal.summary) {
      host.createEl("p", { cls: "kotonoha-console-muted", text: proposal.summary });
    }
    if (proposal.uncertaintyNote) {
      host.createEl("p", {
        cls: "kotonoha-console-warn",
        text: proposal.uncertaintyNote
      });
    }
    const pre = host.createEl("pre", { cls: "kotonoha-console-pre" });
    pre.setText(proposal.proposedText);
    const bar = host.createDiv({ cls: "kotonoha-console-actions" });
    bar.createEl("button", { text: "Apply" }).addEventListener("click", actions.onApply);
    bar.createEl("button", { text: "Reject" }).addEventListener("click", actions.onReject);
    bar.createEl("button", { text: "Copy" }).addEventListener("click", actions.onCopy);
  }
};

// src/ui/RdeAuditView.ts
var RdeAuditView = class {
  constructor(host, audit) {
    host.createEl("h3", { text: "RDE audit" });
    host.createEl("p", {
      text: `Recommended: ${audit.recommendedDecision} \xB7 confidence ${(audit.confidence * 100).toFixed(0)}% (informative)`
    });
    const cats = host.createEl("p", {
      text: `Categories: ${audit.categories.join(", ")}`
    });
    cats.addClass("kotonoha-console-muted");
    appendList(host, "Preserved", audit.preservedElements);
    appendList(host, "Transformed", audit.transformedElements);
    appendList(host, "Inferred", audit.inferredExtensions);
    appendList(host, "Unresolved", audit.unresolvedElements);
    appendList(host, "Drift risks", audit.driftRisks);
  }
};
function appendList(host, title, items) {
  if (items.length === 0) return;
  const section = host.createEl("div");
  section.createEl("strong", { text: title });
  const ul = section.createEl("ul");
  for (const item of items) {
    ul.createEl("li", { text: item });
  }
}

// src/ui/KotonohaConsoleView.ts
var KOTONOHA_CONSOLE_VIEW = "kotonoha-console-view";
var KotonohaConsoleView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  bundle = null;
  proposalHost;
  auditHost;
  instructionInput;
  operationSelect;
  getViewType() {
    return KOTONOHA_CONSOLE_VIEW;
  }
  getDisplayText() {
    return "Kotonoha Console";
  }
  getIcon() {
    return "layers";
  }
  async onOpen() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("kotonoha-console-root");
    containerEl.createEl("h2", { text: "Kotonoha Console" });
    containerEl.createEl("p", {
      cls: "kotonoha-console-muted",
      text: "\u63D0\u6848\u306F\u81EA\u52D5\u9069\u7528\u3055\u308C\u307E\u305B\u3093\u3002Apply \u306E\u524D\u306B\u5185\u5BB9\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
    });
    const ctx = await this.plugin.noteContext.capture();
    if (ctx) {
      const meta = containerEl.createEl("div", { cls: "kotonoha-console-meta" });
      meta.createEl("div", { text: `Note: ${ctx.filePath}` });
      meta.createEl("div", { text: `Source hash: ${ctx.sourceHash.slice(0, 16)}\u2026` });
      if (ctx.selectionText) {
        meta.createEl("div", { text: "Scope: selection" });
      }
      if (ctx.git) {
        meta.createEl("div", {
          text: `Git mode: ${this.plugin.settings.gitMode} \xB7 ${ctx.git.repoRelativePath}`
        });
      }
    } else {
      containerEl.createEl("p", {
        cls: "kotonoha-console-warn",
        text: "\u30A2\u30AF\u30C6\u30A3\u30D6\u306A Markdown \u30CE\u30FC\u30C8\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044\u3002"
      });
    }
    const form = containerEl.createDiv({ cls: "kotonoha-console-form" });
    form.createEl("label", { text: "Operation" });
    this.operationSelect = form.createEl("select");
    for (const op of ["summarize", "rewrite", "expand", "rde_audit", "custom"]) {
      const opt = this.operationSelect.createEl("option", { value: op, text: op });
      opt.value = op;
    }
    form.createEl("label", { text: "Instruction" });
    this.instructionInput = form.createEl("textarea", {
      attr: { rows: "3", placeholder: "\u4EFB\u610F\u306E\u6307\u793A\u2026" }
    });
    const actions = form.createDiv({ cls: "kotonoha-console-actions" });
    actions.createEl("button", { text: "Generate proposal" }).addEventListener(
      "click",
      () => void this.runGenerate()
    );
    this.proposalHost = containerEl.createDiv({ cls: "kotonoha-console-proposal" });
    this.auditHost = containerEl.createDiv({ cls: "kotonoha-console-audit" });
  }
  async onClose() {
    this.containerEl.empty();
  }
  async runGenerate() {
    const ctx = await this.plugin.noteContext.capture();
    if (!ctx) {
      new import_obsidian2.Notice("No active note");
      return;
    }
    const operation = this.operationSelect.value;
    const instruction = this.instructionInput.value.trim();
    const request = this.plugin.generationRequests.create(
      ctx,
      operation,
      instruction,
      this.plugin.settings.defaultLanguage
    );
    try {
      this.bundle = await this.plugin.proposals.generate(request);
      await this.plugin.auditLog.logProposal(
        this.bundle.proposal,
        ctx.sourceText
      );
      this.renderBundle();
      new import_obsidian2.Notice("Proposal ready (not applied)");
    } catch (e) {
      new import_obsidian2.Notice(`Generate failed: ${message(e)}`);
    }
  }
  renderBundle() {
    this.proposalHost.empty();
    this.auditHost.empty();
    if (!this.bundle) return;
    new ProposalView(this.proposalHost, this.bundle.proposal, {
      onApply: () => void this.applyProposal(),
      onReject: () => void this.rejectProposal(),
      onCopy: () => void this.copyProposal()
    });
    if (this.plugin.settings.enableRdeAudit && this.bundle.audit) {
      new RdeAuditView(this.auditHost, this.bundle.audit);
    }
  }
  async applyProposal() {
    if (!this.bundle) return;
    if (this.plugin.settings.requireHumanApproval) {
      const ok = confirm(
        "\u3053\u306E\u63D0\u6848\u3092\u30CE\u30FC\u30C8\u306B\u9069\u7528\u3057\u307E\u3059\u304B\uFF1F\u5143\u306E\u30C6\u30AD\u30B9\u30C8\u306F\u4E0A\u66F8\u304D\u3055\u308C\u307E\u3059\u3002"
      );
      if (!ok) return;
    }
    const ctx = await this.plugin.noteContext.capture();
    if (!ctx) {
      new import_obsidian2.Notice("No active note");
      return;
    }
    const file = this.plugin.activeNoteReader.getActiveFile();
    if (!file) return;
    const text = this.bundle.proposal.proposedText;
    if (ctx.selectionText) {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      const editor = view?.editor;
      if (editor) {
        editor.replaceSelection(text);
      } else {
        new import_obsidian2.Notice("Open note in editor to apply selection");
        return;
      }
    } else {
      await this.plugin.markdownWriter.replaceNoteContent(file, text);
    }
    const decision = this.plugin.approval.approve(this.bundle.proposal, text);
    await this.plugin.auditLog.logDecision(decision, this.bundle.audit);
    new import_obsidian2.Notice("Applied (audit logged)");
    this.bundle = null;
    this.proposalHost.empty();
    this.auditHost.empty();
  }
  async rejectProposal() {
    if (!this.bundle) return;
    const decision = this.plugin.approval.reject(this.bundle.proposal);
    await this.plugin.auditLog.logDecision(decision, this.bundle.audit);
    new import_obsidian2.Notice("Rejected");
    this.bundle = null;
    this.proposalHost.empty();
    this.auditHost.empty();
  }
  async copyProposal() {
    if (!this.bundle) return;
    await navigator.clipboard.writeText(this.bundle.proposal.proposedText);
    new import_obsidian2.Notice("Copied to clipboard");
  }
};
function message(e) {
  return e instanceof Error ? e.message : String(e);
}

// src/util/hash.ts
async function sha256Hex(text) {
  const data = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// src/obsidian/GitContextReader.ts
async function readGitContext(app, file, mode) {
  if (mode === "off") return void 0;
  const repoRelativePath = file.path;
  const dirty = app.vault.getAbstractFileByPath(file.path) !== null;
  return {
    repoRelativePath,
    dirty,
    branch: mode === "passive-observing" ? void 0 : void 0,
    commit: void 0,
    root: vaultBasePath(app) || void 0
  };
}

// src/obsidian/ActiveNoteReader.ts
var ActiveNoteReader = class {
  constructor(app, gitMode) {
    this.app = app;
    this.gitMode = gitMode;
  }
  getActiveFile() {
    const file = this.app.workspace.getActiveFile();
    return file ?? null;
  }
  async readNoteContext(selectionText) {
    const file = this.getActiveFile();
    if (!file) return null;
    const sourceText = await this.app.vault.read(file);
    const targetText = selectionText !== void 0 && selectionText.length > 0 ? selectionText : sourceText;
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache?.frontmatter ?? {};
    const tags = (cache?.tags ?? []).map((t) => t.tag);
    const links = (cache?.links ?? []).map((l) => l.link);
    const git = this.gitMode === "off" ? void 0 : await readGitContext(this.app, file, this.gitMode);
    return {
      vaultPath: vaultBasePath(this.app),
      filePath: file.path,
      title: file.basename,
      sourceText: targetText,
      selectionText: selectionText && selectionText.length > 0 ? selectionText : void 0,
      sourceHash: await sha256Hex(targetText),
      tags,
      links,
      frontmatter,
      git
    };
  }
};

// src/obsidian/MarkdownWriter.ts
var MarkdownWriter = class {
  constructor(app) {
    this.app = app;
  }
  async replaceNoteContent(file, newContent) {
    await this.app.vault.modify(file, newContent);
  }
};

// src/services/NoteContextService.ts
var NoteContextService = class {
  constructor(reader) {
    this.reader = reader;
  }
  async capture(selectionText) {
    return this.reader.readNoteContext(selectionText);
  }
};

// src/services/GenerationRequestService.ts
var GenerationRequestService = class {
  create(context, operation, instruction, language) {
    return {
      id: crypto.randomUUID(),
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      operation,
      instruction,
      context,
      language
    };
  }
};

// src/services/ProposalService.ts
var ProposalService = class {
  constructor(client) {
    this.client = client;
  }
  async generate(request) {
    const result = await this.client.generate(request);
    return { proposal: result.proposal, audit: result.audit };
  }
};

// src/services/ApprovalService.ts
var ApprovalService = class {
  approve(proposal, appliedText, comment) {
    return {
      proposalId: proposal.id,
      decidedAt: (/* @__PURE__ */ new Date()).toISOString(),
      decision: "approved",
      appliedText,
      comment
    };
  }
  reject(proposal, comment) {
    return {
      proposalId: proposal.id,
      decidedAt: (/* @__PURE__ */ new Date()).toISOString(),
      decision: "rejected",
      comment
    };
  }
};

// src/services/AuditLogService.ts
var KOTONOHA_DIR = ".kotonoha/audit";
var AuditLogService = class {
  constructor(app, mode) {
    this.app = app;
    this.mode = mode;
  }
  async logProposal(proposal, sourceExcerpt) {
    const entry = {
      kind: "proposal",
      proposalId: proposal.id,
      createdAt: proposal.createdAt,
      proposalHash: await sha256Hex(proposal.proposedText),
      sourceExcerpt: excerpt(sourceExcerpt, this.mode),
      summary: proposal.summary
    };
    await this.append(entry);
  }
  async logDecision(decision, audit) {
    const entry = {
      kind: "decision",
      ...decision,
      rdeCategories: audit?.categories
    };
    await this.append(entry);
  }
  async append(entry) {
    const name = `${isoFileStamp()}.json`;
    const path = `${KOTONOHA_DIR}/${name}`;
    await this.ensureDir();
    const line = JSON.stringify(entry, null, 2);
    await this.app.vault.adapter.write(path, line);
  }
  async ensureDir() {
    const adapter = this.app.vault.adapter;
    if (!await adapter.exists(KOTONOHA_DIR)) {
      await adapter.mkdir(KOTONOHA_DIR);
    }
  }
};
function isoFileStamp() {
  return (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
}
function excerpt(text, mode) {
  if (mode === "hash_only") return "";
  const max = mode === "summary" ? 200 : 4e3;
  return text.length <= max ? text : `${text.slice(0, max)}\u2026`;
}

// src/cli/proposalFromContextPack.ts
function parseContextPack(stdout) {
  const pack = JSON.parse(stdout);
  if (pack.format !== "kotonoha.context_pack.v0.1") {
    throw new Error(`unexpected context pack format: ${pack.format ?? "(missing)"}`);
  }
  return pack;
}
function proposalTextFromContextPack(request, pack) {
  const anchor = pack.git_anchor;
  const lines = [
    `<!-- kotonoha cli ${request.operation} -->`,
    "",
    `## Operation`,
    request.operation,
    "",
    `## Instruction`,
    request.instruction || "(none)",
    ""
  ];
  if (anchor?.git_commit) {
    lines.push(`## Git anchor`, `- commit: \`${anchor.git_commit}\``, `- file: \`${anchor.file_path ?? request.context.filePath}\``);
    if (anchor.line_range_start != null) {
      lines.push(`- lines: ${anchor.line_range_start}\u2013${anchor.line_range_end ?? anchor.line_range_start}`);
    }
    lines.push("");
  }
  lines.push("## Source", "", request.context.sourceText, "", "---", "", "*CLI mode uses `kotonoha context export` only; connect an orchestrator/LLM for generative rewrite.*");
  return lines.join("\n");
}

// src/cli/proposalFromLocal.ts
function proposalTextFromLocalContext(request) {
  const { context, operation, instruction } = request;
  return [
    `<!-- kotonoha cli-local ${operation} -->`,
    "",
    `## Operation`,
    operation,
    "",
    `## Instruction`,
    instruction || "(none)",
    "",
    `## Anchor (non-Git)`,
    `- path: \`${context.filePath}\``,
    `- source_hash: \`${context.sourceHash.slice(0, 16)}\u2026\``,
    "",
    "## Source",
    "",
    context.sourceText,
    "",
    "---",
    "",
    "*Git-aware `context export` skipped (`gitMode: off` or unavailable). Semantic anchors use path + source hash per git-mode-spec.*"
  ].join("\n");
}

// src/rde/parseRdeEmit.ts
var CATEGORY_MAP = {
  preserved: "preserved",
  complemented: "inferred_extension",
  transformed: "authorized_transformation",
  deviation_risk: "suspicious_drift",
  intentionally_unresolved: "unresolved",
  lost: "critical_distortion",
  next_update_policy: "unresolved"
};
function rdeAuditFromEmit(stdout, proposalId) {
  const root = JSON.parse(stdout);
  const cats = root.rde_review_output?.categories ?? {};
  const categories = /* @__PURE__ */ new Set();
  const preservedElements = [];
  const transformedElements = [];
  const inferredExtensions = [];
  const unresolvedElements = [];
  const driftRisks = [];
  for (const [key, items] of Object.entries(cats)) {
    const mapped = CATEGORY_MAP[key];
    if (mapped) categories.add(mapped);
    const target = key === "preserved" ? preservedElements : key === "transformed" ? transformedElements : key === "complemented" ? inferredExtensions : key === "deviation_risk" ? driftRisks : unresolvedElements;
    for (const item of items ?? []) {
      target.push(String(item));
    }
  }
  if (categories.size === 0) {
    categories.add("unresolved");
  }
  return {
    proposalId,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    categories: [...categories],
    preservedElements,
    transformedElements,
    inferredExtensions,
    unresolvedElements,
    driftRisks,
    recommendedDecision: "human_review",
    confidence: 0.5
  };
}

// src/rde/enrichAuditFromSource.ts
function enrichAuditFromSource(audit, request) {
  const excerpt2 = request.context.sourceText.slice(0, 200).replace(/\n/g, " ") + (request.context.sourceText.length > 200 ? "\u2026" : "");
  return {
    ...audit,
    preservedElements: [
      `path:${request.context.filePath}`,
      `source_hash:${request.context.sourceHash.slice(0, 16)}\u2026`,
      excerpt2,
      ...audit.preservedElements
    ],
    driftRisks: audit.driftRisks.length > 0 ? audit.driftRisks : ["Review source vs RDE skeleton \u2014 no Git commit boundary"]
  };
}

// src/rde/rdeAuditReport.ts
function rdeAuditReportMarkdown(request, audit) {
  const lines = [
    `<!-- kotonoha rde-audit -->`,
    "",
    `# RDE audit`,
    "",
    `**File:** \`${request.context.filePath}\``,
    `**Source hash:** \`${request.context.sourceHash.slice(0, 16)}\u2026\``,
    `**Recommended:** ${audit.recommendedDecision}`,
    "",
    "## Categories",
    audit.categories.join(", ") || "(none)",
    ""
  ];
  appendSection(lines, "Preserved", audit.preservedElements);
  appendSection(lines, "Transformed", audit.transformedElements);
  appendSection(lines, "Inferred", audit.inferredExtensions);
  appendSection(lines, "Unresolved", audit.unresolvedElements);
  appendSection(lines, "Drift risks", audit.driftRisks);
  lines.push("## Source excerpt", "", request.context.sourceText.slice(0, 2e3));
  if (request.context.sourceText.length > 2e3) {
    lines.push("", "\u2026");
  }
  return lines.join("\n");
}
function appendSection(lines, title, items) {
  if (items.length === 0) return;
  lines.push(`## ${title}`, "");
  for (const item of items) {
    lines.push(`- ${item}`);
  }
  lines.push("");
}

// src/client/CliKotonohaClient.ts
var CliKotonohaClient = class {
  constructor(options) {
    this.options = options;
    this.runner = options.runner ?? runKotonoha;
  }
  runner;
  async generate(request) {
    await this.assertCliAvailable();
    const proposalId = crypto.randomUUID();
    if (request.operation === "rde_audit") {
      return this.generateRdeAudit(request, proposalId);
    }
    if (this.mayUseContextExport()) {
      try {
        return await this.generateWithContextExport(request, proposalId);
      } catch (e) {
        const fallback = this.generateLocal(request, proposalId);
        fallback.proposal.uncertaintyNote = [
          "Git-aware context export failed; using path + source_hash anchors.",
          e instanceof Error ? e.message : String(e)
        ].join(" ");
        return fallback;
      }
    }
    return this.generateLocal(request, proposalId);
  }
  /** git-mode-spec §10: non-Git mode must not require Git-aware CLI. */
  mayUseContextExport() {
    return this.options.gitMode !== "off";
  }
  async generateRdeAudit(request, proposalId) {
    const emitResult = await this.run({ args: ["rde", "emit"] });
    if (emitResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(emitResult));
    }
    const validateResult = await this.run({
      args: ["rde", "validate", "--strict"],
      stdin: emitResult.stdout
    });
    if (validateResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(validateResult));
    }
    const audit = enrichAuditFromSource(
      rdeAuditFromEmit(emitResult.stdout, proposalId),
      request
    );
    const proposedText = rdeAuditReportMarkdown(request, audit);
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText,
        summary: `[cli] RDE audit \xB7 ${request.context.filePath}`,
        uncertaintyNote: "RDE audit uses `rde emit` + `rde validate` only (no Git). Attach via DB workflow when DATABASE_URL is configured."
      },
      audit
    };
  }
  async generateWithContextExport(request, proposalId) {
    const relFile = request.context.filePath;
    const args = ["context", "export", relFile, "--path", this.options.cwd];
    const obsPath = await this.maybeObservationPath(request);
    if (obsPath) args.push("--observation", obsPath);
    const packResult = await this.run({ args });
    if (packResult.exitCode !== 0) {
      throw new Error(cliErrorMessage(packResult));
    }
    const pack = parseContextPack(packResult.stdout);
    const proposedText = proposalTextFromContextPack(request, pack);
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText,
        summary: `[cli] context export \xB7 ${request.operation} \xB7 ${relFile}`,
        uncertaintyNote: "Generative rewrite requires an orchestrator/LLM; proposal embeds `kotonoha context export`."
      }
    };
  }
  generateLocal(request, proposalId) {
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText: proposalTextFromLocalContext(request),
        summary: `[cli-local] ${request.operation} \xB7 ${request.context.filePath}`,
        uncertaintyNote: this.options.gitMode === "off" ? "gitMode is off \u2014 Git-aware CLI not used (git-mode-spec \xA74)." : "Local anchors only (path + source_hash)."
      }
    };
  }
  async assertCliAvailable() {
    const result = await this.run({ args: ["version"] });
    if (result.exitCode !== 0) {
      throw new Error(
        `kotonoha not available (${this.options.bin}): ${cliErrorMessage(result)}`
      );
    }
  }
  async maybeObservationPath(request) {
    if (!this.options.writeObservation) return void 0;
    const hasInstruction = request.instruction.trim().length > 0;
    if (!hasInstruction && request.operation === "custom") return void 0;
    return this.options.writeObservation({
      operation: request.operation,
      instruction: request.instruction,
      source_hash: request.context.sourceHash
    });
  }
  run(partial) {
    return this.runner({
      bin: this.options.bin,
      cwd: this.options.cwd,
      env: this.options.env,
      args: partial.args,
      stdin: partial.stdin
    });
  }
};

// src/client/MockKotonohaClient.ts
function id() {
  return crypto.randomUUID();
}
var MockKotonohaClient = class {
  async generate(request) {
    const { context, operation, instruction } = request;
    const excerpt2 = context.sourceText.slice(0, 120).replace(/\n/g, " ") + (context.sourceText.length > 120 ? "\u2026" : "");
    const proposedText = [
      `<!-- kotonoha mock ${operation} -->`,
      "",
      `> ${instruction || "(no instruction)"}`,
      "",
      context.sourceText
    ].join("\n");
    const proposalId = id();
    const audit = {
      proposalId,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      categories: ["preserved", "authorized_transformation"],
      preservedElements: [excerpt2],
      transformedElements: [`mock ${operation} wrapper`],
      inferredExtensions: [],
      unresolvedElements: [],
      driftRisks: [],
      recommendedDecision: "human_review",
      confidence: 0.55
    };
    return {
      proposal: {
        id: proposalId,
        requestId: request.id,
        createdAt: (/* @__PURE__ */ new Date()).toISOString(),
        proposedText,
        summary: `[mock] ${operation} on ${context.title}`,
        uncertaintyNote: "Mock backend \u2014 connect HTTP or CLI in settings for real Kotonoha output."
      },
      audit
    };
  }
};

// src/client/createClient.ts
var OBSERVATION_REL = ".kotonoha/cli-observation.json";
function createKotonohaClient(settings, app) {
  switch (settings.backendMode) {
    case "cli": {
      const cwd = settings.cliWorkdir?.trim() || vaultBasePath(app) || process.cwd();
      return new CliKotonohaClient({
        bin: settings.cliCommand?.trim() || "kotonoha",
        cwd,
        gitMode: settings.gitMode,
        env: buildCliEnv(settings),
        writeObservation: async (payload) => {
          const dir = ".kotonoha";
          const adapter = app.vault.adapter;
          if (!await adapter.exists(dir)) {
            await adapter.mkdir(dir);
          }
          await adapter.write(
            OBSERVATION_REL,
            JSON.stringify(payload, null, 2)
          );
          return OBSERVATION_REL;
        }
      });
    }
    case "mock":
      return new MockKotonohaClient();
    case "http":
      return new MockKotonohaClient();
    default:
      return new MockKotonohaClient();
  }
}

// src/main.ts
var KotonohaConsolePlugin = class extends import_obsidian3.Plugin {
  settings = { ...DEFAULT_SETTINGS };
  activeNoteReader;
  markdownWriter;
  noteContext;
  generationRequests = new GenerationRequestService();
  proposals;
  approval = new ApprovalService();
  auditLog;
  client;
  async onload() {
    await this.loadSettings();
    this.refreshNoteReader();
    this.markdownWriter = new MarkdownWriter(this.app);
    this.noteContext = new NoteContextService(this.activeNoteReader);
    this.refreshClient();
    this.refreshAuditLog();
    this.registerView(KOTONOHA_CONSOLE_VIEW, (leaf) => new KotonohaConsoleView(leaf, this));
    this.addRibbonIcon("layers", "Kotonoha Console", () => {
      void this.activateConsole();
    });
    this.addCommand({
      id: "open-console",
      name: "Open Kotonoha Console",
      callback: () => void this.activateConsole()
    });
    this.addCommand({
      id: "generate-mock-proposal",
      name: "Generate mock proposal (active note)",
      callback: () => void this.activateConsole()
    });
    this.addSettingTab(new KotonohaSettingsTab(this.app, this));
  }
  refreshNoteReader() {
    this.activeNoteReader = new ActiveNoteReader(this.app, this.settings.gitMode);
  }
  refreshClient() {
    this.client = createKotonohaClient(this.settings, this.app);
    this.proposals = new ProposalService(this.client);
  }
  refreshAuditLog() {
    this.auditLog = new AuditLogService(this.app, this.settings.auditLogMode);
  }
  async activateConsole() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(KOTONOHA_CONSOLE_VIEW)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right) return;
      await right.setViewState({ type: KOTONOHA_CONSOLE_VIEW, active: true });
      leaf = right;
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...await this.loadData()
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async testCliVersion() {
    const bin = this.settings.cliCommand?.trim() || "kotonoha";
    const cwd = this.settings.cliWorkdir?.trim() || vaultBasePath(this.app) || ".";
    try {
      const result = await runKotonoha({
        bin,
        cwd,
        args: ["version"],
        env: buildCliEnv(this.settings)
      });
      if (result.exitCode === 0) {
        new import_obsidian3.Notice(result.stdout.trim().split("\n")[0] ?? "kotonoha ok");
      } else {
        new import_obsidian3.Notice(`CLI error: ${cliErrorMessage(result)}`);
      }
    } catch (e) {
      new import_obsidian3.Notice(`CLI spawn failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
};
